## WARNING ########################################
#                                                 #
# ONLY EDIT THE SCAN SECTION IF YOU KNOW WHAT     #
# YOU ARE DOING, HAVING THE NUMBERS TOO LOW       #
# WILL RESULT IN INNOCENT PLAYERS BEING AFFECTED! #
#                                                 #
######################################## WARNING ##

checks:
  illegalMovement:
    # How far are you allowed to move in one packet when riding something (-1 to disable check)
    distance: 25

scan:
  # How often the total chunks loaded is tallied in seconds
  # Default: 2
  time: 2
  
  # How many chunks must be loaded to "trigger" the punishment
  # Default: 200
  chunkThreshold: 200

detection:
  # The commands ran when a player is detected
  # %player% will be replaced with the players name
  commands:
  - 'ban %player% Illegal movement (Boat exploit?)'
  # Whether chunks should be cleaned up (unloaded) when a player is detected
  # Default: true
  chunkCleanup: true