name: NoMoreBoatExploit
version: 1.1.0
description: 'A simple plugin to remove a very unfriendly boat exploit'
author: CraigEge
website: 'https://github.com/CraigEge/NoMoreBoatExploit'

main: com.craigegerton.nomoreboatexploit.NoMoreBoatExploit